#frase = 'Curso em Vídeo Python'
#print(frase.upper().count(''))
#print(len(frase.strip()))
#frase = (frase.replace('em', 'no'))
#print(frase)
#print('curso' in frase.lower())
#print(frase.find('em'))
#print(frase.find('Vídeo'))
#dividido = (frase.split())
#print(dividido[0][2])
a = str(input('Digite seu nome completo:').strip())
print(a.upper())
print(a.lower())
#am = a.replace(' ','')

am = a.strip()
print(am)
print(am.count(''))
#ar = a.split()
#print(ar)
#print()